spring:

  datasource:
    url:  jdbc:h2:mem:testdb
    username: admin
    password: admin012
    driverClassName:  org.h2.Driver

  jpa:
    datatabase-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql:  true
    properties.hibernate.format_sql:  true

  h2:
    console:
      enabled: true
      path: /condominio